import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <aside className=" hidden md:block w-80 h-screen sticky top-0">
         <Sidebar/>
        </aside>
        <main className="flex-1 bg-[#f8f9fe] ">
        
        <Header/>
         

        
        {children}
        <Footer/>
        </main>
       
        </body>
    </html>
  );
}
